name: QA
on: pull_request
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
