name: Bug Report
description: Create a report to help us improve the Saleor React Storefront
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Using this template makes it a lot easier for us to diagnose your problem, so please fill in as many fields as possible.

  - type: textarea
    id: description
    attributes:
      label: Summary
      description: A short description of the problem
      placeholder: |
        Include what you expected to happen, and what actually happened.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: link-to-reproduction
    attributes:
      label: A link to a reproduction repository
      description: The fastest way to describe your bug is to provide a reproduction repository.
      placeholder: https://github.com/project/link-to-your-reproduction-repo

  - type: textarea
    id: env
    attributes:
      label: Output from envinfo
      description: |
        To get the environment information from your desktop use this command and paste it here:
        `npx envinfo --system --binaries --browsers --markdown`

        Please also provide the version of pnpm you're using:
        `pnpm --version`
