name: Build, TypeScripts, tests
on: [pull_request]

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      SALEOR_API_URL: ${{ vars.SALEOR_API_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Get PNPM version from package.json
        id: pnpm-version
        run: echo "pnpm_version=$(cat package.json | jq '.engines.pnpm' | sed -E 's/[^0-9.]//g')" >> $GITHUB_OUTPUT

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm --version && pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
