name: "Close stale issues and PR"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 7
          days-before-close: 7
          days-before-pr-close: -1
